[package]
name = "trinket-examples"
version = "0.0.0"
authors = ["Jan Paw <jpaw@virtuslab.com>"]
edition = "2021"
publish = false

[dependencies]
panic-halt = "1.0.0"
embedded-hal = "1.0"

[dependencies.arduino-hal]
path = "../../arduino-hal/"
features = ["trinket"]
